apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 80.9.2
    releaseName: monitoring
    namespace: monitoring
    includeCRDs: true
    valuesFile: "values.yaml"

patchesJson6902:
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: prometheuses.monitoring.coreos.com
    patch: |-
      - op: add
        path: "/metadata/annotations/argocd.argoproj.io~1sync-options"
        value: "Replace=true"
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: prometheusagents.monitoring.coreos.com
    patch: |-
      - op: add
        path: "/metadata/annotations/argocd.argoproj.io~1sync-options"
        value: "Replace=true"
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: scrapeconfigs.monitoring.coreos.com
    patch: |-
      - op: add
        path: "/metadata/annotations/argocd.argoproj.io~1sync-options"
        value: "Replace=true"
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: thanosrulers.monitoring.coreos.com
    patch: |-
      - op: add
        path: "/metadata/annotations/argocd.argoproj.io~1sync-options"
        value: "Replace=true"
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: alertmanagerconfigs.monitoring.coreos.com
    patch: |-
      - op: add
        path: "/metadata/annotations/argocd.argoproj.io~1sync-options"
        value: "Replace=true"
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: alertmanagers.monitoring.coreos.com
    patch: |-
      - op: add
        path: "/metadata/annotations/argocd.argoproj.io~1sync-options"
        value: "Replace=true"


resources:
  - ingress.yaml